import type { TacticalBriefing, BriefingsBundle } from './types';
import type { Season, WaterClarity, FrontalSystem } from '../types';

// Import the pre-generated briefings bundle at build time
// This will be a static JSON file generated by the knowledge pipeline
let briefingsMap: Map<string, TacticalBriefing> | null = null;

// Map frontal systems to pressure states used in briefings
function toPressureState(frontal: FrontalSystem): string {
  switch (frontal) {
    case 'pre-frontal': return 'pre-frontal';
    case 'post-frontal': case 'cold-front': return 'post-frontal';
    case 'stable': return 'stable';
  }
}

// Map lure names to kebab-case slugs used in briefing keys
export const LURE_TO_SLUG: Record<string, string> = {
  'Squarebill Crankbait': 'squarebill-crankbait',
  'Medium Diving Crankbait': 'medium-diving-crankbait',
  'Deep Diving Crankbait': 'deep-diving-crankbait',
  'Lipless Crankbait': 'lipless-crankbait',
  'Suspending Jerkbait': 'suspending-jerkbait',
  'Spinnerbait (Colorado/Willow)': 'spinnerbait',
  'Chatterbait': 'chatterbait',
  'Bladed Jig': 'chatterbait',
  'Swim Jig': 'swim-jig',
  'Flipping Jig': 'flipping-jig',
  'Football Jig': 'football-jig',
  'Texas Rig (Creature Bait)': 'texas-rig',
  'Carolina Rig': 'carolina-rig',
  '10" Worm (Shakey/TX)': 'ten-inch-worm',
  'Drop Shot': 'drop-shot',
  'Ned Rig': 'ned-rig',
  'Neko Rig': 'neko-rig',
  'Shakyhead': 'shakyhead',
  'Walking Topwater': 'walking-topwater',
  'Buzzbait': 'walking-topwater',
  'Hollow-Body Frog': 'walking-topwater',
};

// Keep LURE_TO_CATEGORY for backward compatibility with other parts of the app
export const LURE_TO_CATEGORY: Record<string, string> = {
  'Squarebill Crankbait': 'cranking',
  'Medium Diving Crankbait': 'cranking',
  'Deep Diving Crankbait': 'cranking',
  'Lipless Crankbait': 'cranking',
  'Suspending Jerkbait': 'cranking',
  'Drop Shot': 'finesse',
  'Ned Rig': 'finesse',
  'Neko Rig': 'finesse',
  'Shakyhead': 'finesse',
  'Spy Bait': 'finesse',
  'Flipping Jig': 'jigs',
  'Structure Jig': 'jigs',
  'Football Jig': 'jigs',
  'Hair Jig / Finesse Jig': 'jigs',
  'Crawfish Pattern Jig': 'jigs',
  'Swim Jig': 'moving-baits',
  'Spinnerbait (Colorado/Willow)': 'moving-baits',
  'Bladed Jig': 'moving-baits',
  'Strolling Rig': 'moving-baits',
  'Walking Topwater': 'topwater',
  'Buzzbait': 'topwater',
  'Hollow-Body Frog': 'topwater',
  'Blade Bait': 'reaction',
  'Jigging Spoon': 'reaction',
  'Texas Rig (Creature Bait)': 'soft-plastics',
  'Carolina Rig': 'soft-plastics',
  '10" Worm (Shakey/TX)': 'soft-plastics',
};

function buildKey(season: string, clarity: string, pressure: string, lureSlug: string): string {
  return `${season}_${clarity}_${pressure}_${lureSlug}`;
}

function loadBriefings(): Map<string, TacticalBriefing> {
  if (briefingsMap) return briefingsMap;

  briefingsMap = new Map();

  try {
    // Static import of the generated bundle (copied from knowledge pipeline output)
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const bundle: BriefingsBundle = require('../../data/briefings-bundle.json');
    for (const b of bundle.briefings) {
      // Key by lure slug — the bundle uses lure names, we need to slugify
      const slug = LURE_TO_SLUG[b.conditions.lure];
      if (!slug) continue;
      const key = buildKey(
        b.conditions.season,
        b.conditions.waterClarity,
        b.conditions.pressureState,
        slug,
      );
      briefingsMap.set(key, b);
    }
  } catch {
    // Bundle not yet generated — return empty map
  }

  return briefingsMap;
}

/** Get the lure category for a given lure name */
export function getLureCategory(lureName: string): string | undefined {
  return LURE_TO_CATEGORY[lureName];
}

/** Get all available lure categories */
export function getAvailableCategories(): string[] {
  return ['cranking', 'finesse', 'jigs', 'moving-baits', 'topwater', 'reaction', 'soft-plastics'];
}

/**
 * Look up a pre-generated tactical briefing for the given lure and conditions.
 * Falls back progressively: drops pressure first, then clarity.
 */
export function getBriefing(
  season: Season,
  clarity: WaterClarity,
  frontalSystem: FrontalSystem,
  lureName: string,
): TacticalBriefing | null {
  const map = loadBriefings();
  if (map.size === 0) return null;

  const pressure = toPressureState(frontalSystem);
  const slug = LURE_TO_SLUG[lureName];
  if (!slug) return null;

  // Exact match
  const exact = map.get(buildKey(season, clarity, pressure, slug));
  if (exact) return exact;

  // Fallback 1: drop pressure → stable
  const f1 = map.get(buildKey(season, clarity, 'stable', slug));
  if (f1) return f1;

  // Fallback 2: drop clarity → stained (most common)
  const f2 = map.get(buildKey(season, 'stained', pressure, slug));
  if (f2) return f2;

  // Fallback 3: drop both
  const f3 = map.get(buildKey(season, 'stained', 'stable', slug));
  if (f3) return f3;

  return null;
}

/**
 * Get briefings for specific lure names.
 */
export function getBriefingsForAnalysis(
  season: Season,
  clarity: WaterClarity,
  frontalSystem: FrontalSystem,
  topLureNames: string[],
): { lure: string; briefing: TacticalBriefing }[] {
  const results: { lure: string; briefing: TacticalBriefing }[] = [];

  for (const lureName of topLureNames) {
    const briefing = getBriefing(season, clarity, frontalSystem, lureName);
    if (briefing) {
      results.push({ lure: lureName, briefing });
    }
  }

  return results;
}

export type { TacticalBriefing, BriefingApproach, ProInsight, BriefingConditions } from './types';
