import type { TacticalBriefing, BriefingsBundle } from './types';
import type { Season, WaterClarity, FrontalSystem } from '../types';

// Import the pre-generated briefings bundle at build time
// This will be a static JSON file generated by the knowledge pipeline
let briefingsMap: Map<string, TacticalBriefing> | null = null;

// Map frontal systems to pressure states used in briefings
function toPressureState(frontal: FrontalSystem): string {
  switch (frontal) {
    case 'pre-frontal': return 'pre-frontal';
    case 'post-frontal': case 'cold-front': return 'post-frontal';
    case 'stable': return 'stable';
  }
}

// Map lure names to briefing lure categories
const LURE_TO_CATEGORY: Record<string, string> = {
  'Squarebill Crankbait': 'cranking',
  'Medium Diving Crankbait': 'cranking',
  'Deep Diving Crankbait': 'cranking',
  'Lipless Crankbait': 'cranking',
  'Suspending Jerkbait': 'cranking',
  'Drop Shot': 'finesse',
  'Ned Rig': 'finesse',
  'Neko Rig': 'finesse',
  'Shakyhead': 'finesse',
  'Spy Bait': 'finesse',
  'Flipping Jig': 'jigs',
  'Structure Jig': 'jigs',
  'Football Jig': 'jigs',
  'Hair Jig / Finesse Jig': 'jigs',
  'Crawfish Pattern Jig': 'jigs',
  'Swim Jig': 'moving-baits',
  'Spinnerbait (Colorado/Willow)': 'moving-baits',
  'Chatterbait': 'moving-baits',
  'Strolling Rig': 'moving-baits',
  'Walking Topwater': 'topwater',
  'Buzzbait': 'topwater',
  'Blade Bait': 'reaction',
  'Jigging Spoon': 'reaction',
  'Texas Rig (Creature Bait)': 'soft-plastics',
  'Carolina Rig': 'soft-plastics',
  '10" Worm (Shakey/TX)': 'soft-plastics',
};

function buildKey(season: string, clarity: string, pressure: string, category: string): string {
  return `${season}_${clarity}_${pressure}_${category}`;
}

function loadBriefings(): Map<string, TacticalBriefing> {
  if (briefingsMap) return briefingsMap;

  briefingsMap = new Map();

  try {
    // Static import of the generated bundle (copied from knowledge pipeline output)
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const bundle: BriefingsBundle = require('../../data/briefings-bundle.json');
    for (const b of bundle.briefings) {
      const key = buildKey(
        b.conditions.season,
        b.conditions.waterClarity,
        b.conditions.pressureState,
        b.conditions.lureCategory,
      );
      briefingsMap.set(key, b);
    }
  } catch {
    // Bundle not yet generated — return empty map
  }

  return briefingsMap;
}

/** Get the lure category for a given lure name */
export function getLureCategory(lureName: string): string | undefined {
  return LURE_TO_CATEGORY[lureName];
}

/** Get all available lure categories */
export function getAvailableCategories(): string[] {
  return ['cranking', 'finesse', 'jigs', 'moving-baits', 'topwater', 'reaction', 'soft-plastics'];
}

/**
 * Look up a pre-generated tactical briefing for the given conditions.
 * Falls back progressively: drops pressure first, then clarity.
 */
export function getBriefing(
  season: Season,
  clarity: WaterClarity,
  frontalSystem: FrontalSystem,
  lureCategory: string,
): TacticalBriefing | null {
  const map = loadBriefings();
  if (map.size === 0) return null;

  const pressure = toPressureState(frontalSystem);

  // Exact match
  const exact = map.get(buildKey(season, clarity, pressure, lureCategory));
  if (exact) return exact;

  // Fallback 1: drop pressure → stable
  const f1 = map.get(buildKey(season, clarity, 'stable', lureCategory));
  if (f1) return f1;

  // Fallback 2: drop clarity → stained (most common)
  const f2 = map.get(buildKey(season, 'stained', pressure, lureCategory));
  if (f2) return f2;

  // Fallback 3: drop both
  const f3 = map.get(buildKey(season, 'stained', 'stable', lureCategory));
  if (f3) return f3;

  return null;
}

/**
 * Get briefings for the top N lure categories relevant to current conditions.
 */
export function getBriefingsForAnalysis(
  season: Season,
  clarity: WaterClarity,
  frontalSystem: FrontalSystem,
  topLureNames: string[],
): { category: string; briefing: TacticalBriefing }[] {
  const seen = new Set<string>();
  const results: { category: string; briefing: TacticalBriefing }[] = [];

  for (const lureName of topLureNames) {
    const category = LURE_TO_CATEGORY[lureName];
    if (!category || seen.has(category)) continue;
    seen.add(category);

    const briefing = getBriefing(season, clarity, frontalSystem, category);
    if (briefing) {
      results.push({ category, briefing });
    }
  }

  return results;
}

export type { TacticalBriefing, BriefingApproach, ProInsight, BriefingConditions } from './types';
