import type { MergedReview } from './types';

export function generateProfile(id: string, name: string, data: MergedReview): string {
  const opinions = Object.values(data.opinions).map(op => {
    const tipRules = op.tipRules.map(tr => ({
      when: tr.when,
      tip: tr.tip,
      priority: tr.priority,
    }));

    const colorRules = op.colorRules.map(cr => ({
      when: cr.when,
      color: cr.color,
      hex: cr.hex,
      priority: cr.priority,
    }));

    const confidenceModifiers = op.confidenceModifiers.map(cm => ({
      when: cm.when,
      adjustment: cm.adjustment,
    }));

    const result: Record<string, unknown> = {
      lure: op.lure,
    };

    if (op.seasonAdd?.length) result.seasonAdd = op.seasonAdd;
    if (op.minTempOverride != null) result.minTempOverride = op.minTempOverride;
    if (op.maxFishDepthOverride != null) result.maxFishDepthOverride = op.maxFishDepthOverride;
    if (confidenceModifiers.length) result.confidenceModifiers = confidenceModifiers;
    if (colorRules.length) result.colorRules = colorRules;
    if (tipRules.length) result.tipRules = tipRules;
    if (op.defaultTips?.[0]?.tip) result.defaultTip = op.defaultTips[0].tip;

    return result;
  });

  // Build credibility map — source data may be Record<string, {score,source}[]> or Record<string, number>
  const credibility: Record<string, number> = {};
  if (data.credibility && typeof data.credibility === 'object' && !Array.isArray(data.credibility)) {
    for (const [lure, val] of Object.entries(data.credibility)) {
      if (typeof val === 'number') {
        credibility[lure] = val;
      } else if (Array.isArray(val) && val.length > 0) {
        // Average the scores from multiple sources
        const scores = val.map((v: { score: number }) => v.score).filter((s: number) => typeof s === 'number');
        credibility[lure] = scores.length > 0
          ? Math.round((scores.reduce((a: number, b: number) => a + b, 0) / scores.length) * 100) / 100
          : 0.5;
      }
    }
  }

  // Build structure advice
  const structureAdvice: Record<string, string> = {};
  if (data.structureAdvice && typeof data.structureAdvice === 'object') {
    for (const [type, entries] of Object.entries(data.structureAdvice)) {
      if (Array.isArray(entries) && entries.length > 0) {
        structureAdvice[type] = entries[0].advice;
      }
    }
  }

  const profile = {
    name,
    id,
    credibility,
    defaultCredibility: 0.5,
    opinions,
    ...(Object.keys(structureAdvice).length > 0 ? { structureAdvice } : {}),
  };

  const json = JSON.stringify(profile, null, 2);

  // Build TypeScript output
  const lines = [
    `// ─── ${name} Angler Profile ───`,
    `// Auto-generated by knowledge review tool`,
    `import type { AnglerProfile } from './types';`,
    ``,
    `export const ${id}: AnglerProfile = ${json};`,
    ``,
  ];

  return lines.join('\n');
}
